version: '3'

networks:
  lumen:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mongo
    networks:
      - lumen

mssql:
        build:
          context: ./mssql
        environment:
          - MSSQL_PID=Express
          - MSSQL_DATABASE=${MSSQL_DATABASE}
          - SA_PASSWORD=${MSSQL_PASSWORD}
          - ACCEPT_EULA=Y
        volumes:
          - ${DATA_PATH_HOST}/mssql:/var/opt/mssql
        ports:
          - "${MSSQL_PORT}:1433"
        networks:
          - backend

  mongo:
        build: ./mongo
        ports:
          - "${MONGODB_PORT}:27017"
        volumes:
          - ${DATA_PATH_HOST}/mongo:/data/db
          - ${DATA_PATH_HOST}/mongo_config:/data/configdb
        networks:
          - backend  

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - lumen

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - lumen

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: lumen
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - lumen

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - lumen

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: lumen
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - lumen

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - lumen
